spring:
  datasource:
    url: jdbc:h2:mem:event_sourcing_demo
    driverClassName: org.h2.Driver
    username: sa
    password:
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/testdata