create table persistent_event
(
    id           bigint generated by default as identity,
    aggregate_id uuid         not null,
    create_date  timestamp(6) not null,
    payload      varchar(255) not null,
    type         varchar(255) not null,
    primary key (id)
);

create table account_projection
(
    id             uuid           not null,
    account_number varchar(255)   not null,
    balance        numeric(38, 2) not null,
    credit_line    numeric(38, 2) not null,
    primary key (id)
);